#!/usr/bin/env python3
"""Writes ios-apps/Shared/Translations.swift from docs/i18n.js, so the iPad app and the phone check-in share one set
of translations. Run it after editing docs/i18n.js, then run ./sync-shared.sh.

Needs Node.js (to read the JavaScript file)."""
import json
import pathlib
import subprocess

HERE = pathlib.Path(__file__).resolve().parent
SOURCE = HERE.parent / "docs" / "i18n.js"
TARGET = HERE / "Shared" / "Translations.swift"

data = json.loads(subprocess.run(
    ["node", "-e", "global.window = {}; require(process.argv[1]); console.log(JSON.stringify(window.SEREN_I18N))", str(SOURCE)],
    check=True, capture_output=True, text=True).stdout)


def swift(text):
    return json.dumps(text, ensure_ascii=False)


def block(entries):
    lines = []
    for english, langs in entries.items():
        pairs = ", ".join(f"{swift(code)}: {swift(value)}" for code, value in langs.items())
        lines.append(f"        {swift(english)}: [{pairs}],")
    return "\n".join(lines)


general = {**data["strings"], **data.get("app", {})}
TEMPLATE = """// Shared source — edit in ios-apps/Shared, then run ios-apps/sync-shared.sh.
// GENERATED by ios-apps/make-translations.py from docs/i18n.js. Don't edit by hand: change docs/i18n.js and rerun it.

import Foundation

/// Chinese, Korean, French, Japanese and Russian wording, keyed by the English text. `L(...)` looks strings up here.
/// Strings that include the business name are keyed with "Seren" (the default name).
enum Translations {
    static let table: [String: [String: String]] = general.merging(health) { first, _ in first }

    private static let general: [String: [String: String]] = [
@GENERAL@
    ]

    /// ⚠ Health, contraindication and consent wording. Not yet checked by native speakers.
    private static let health: [String: [String: String]] = [
@HEALTH@
    ]
}
"""
TARGET.write_text(TEMPLATE.replace("@GENERAL@", block(general)).replace("@HEALTH@", block(data["health"])), encoding="utf-8")
print(f"Wrote {TARGET.relative_to(HERE.parent)}: {len(general)} general + {len(data['health'])} health strings")
